### ISSUE TITLE
Update createRule snippets

### ISSUE THREAD

**Issue by szarnyasg** [viatra/viatra-docs#10]
Some code snippets do not compile with VIATRA 1.2/1.3/1.4 as `createRule` does not take an argument.

`val hostRule = createRule(HostInstanceMatcher.querySpecification)`

`val applicationRule = createRule(ApplicationInstanceMatcher.querySpecification) [
    val cpsApplicationInstance = it.appInstance
...`

**Comment by ujhelyiz** [comment]
Fixed in master.
