### ISSUE TITLE
Add example image from the VIATRA Viewers

### ISSUE THREAD

**Issue by tamasborbas** [viatra/viatra-docs#11]
It could be nice if you add an example picture from the VIATRA Viewers in progress at the VIATRA Viewers chapter ([link](http://static.incquerylabs.com/projects/viatra/viatra-docs/ViatraDocs.html#_viatra_viewers) to the chapter) like on eclipse wiki ([link](https://wiki.eclipse.org/VIATRA/Addon/VIATRA_Viewers#Zest_Graph_Viewer_example) to wiki.eclipse.org).

**Comment by ujhelyiz** [comment]
Won't fix here; if still necessary, the issue can be handled at eclipse.org
