### ISSUE TITLE
Provide syntax highlight for VIATRA code snippets

### ISSUE THREAD

**Issue by ujhelyiz** [viatra/viatra-docs#3]
We should look at how can we add syntax highlight to VIATRA Query and Transformation codes, as the Java highlighter we are using is not good enough for graph patterns and Xtend code. Follow-up ticket from #2.

**Comment by ujhelyiz** [comment]
The syntax highlight used by #4 works only on HTML; the PDF version will have no syntax highlight.

**Comment by tamasborbas** [comment]
Try this for pdf generation in the Rakefile:

`bundle exec asciidoctor-pdf -a pdf-stylesdir=./ -a pdf-style=basic  source-highlighter=coderay ViatraDocs.asciidoc`

Maybe syntax highlight will work for Java and other common languages in pdf (for vql I have no solution yet).
